<?php

return [
    'enabled' => env('DEBUGBAR_ENABLED', env('APP_ENV') === 'local'),
    'collect_jobs' => false,
    'except' => [
        'telescope*',
        'horizon*',
        '_boost/browser-logs',
        'livewire-*/livewire.js',
    ],
    'collectors' => [
        'phpinfo' => false,
        'messages' => false,
        'time' => true,
        'memory' => true,
        'exceptions' => true,
        'log' => false,
        'db' => true,
        'views' => false,
        'route' => true,
        'auth' => false,
        'gate' => false,
        'session' => false,
        'symfony_request' => false,
        'mail' => false,
        'laravel' => true,
        'events' => false,
        'logs' => false,
        'config' => false,
        'cache' => true,
        'models' => true,
        'livewire' => false,
        'inertia' => false,
        'jobs' => false,
        'pennant' => false,
        'http_client' => false,
    ],
    'options' => [
        'time' => [
            'memory_usage' => false,
        ],
        'db' => [
            'with_params' => true,
            'exclude_paths' => [],
            'backtrace' => true,
            'backtrace_exclude_paths' => [],
            'timeline' => true,
            'duration_background' => true,
            'explain' => [
                'enabled' => env('DEBUGBAR_OPTIONS_DB_EXPLAIN_ENABLED', true),
            ],
            'show_query_result' => false,
            'only_slow_queries' => false,
            'slow_threshold' => (int) env('DEBUGBAR_OPTIONS_DB_SLOW_THRESHOLD', 50),
            'memory_usage' => false,
            'soft_limit' => (int) env('DEBUGBAR_OPTIONS_DB_SOFT_LIMIT', 200),
            'hard_limit' => (int) env('DEBUGBAR_OPTIONS_DB_HARD_LIMIT', 500),
        ],
        'cache' => [
            'values' => false,
            'timeline' => true,
        ],
        'views' => [
            'timeline' => false,
            'data' => false,
            'group' => 50,
            'exclude_paths' => [],
        ],
        'route' => [
            'label' => true,
        ],
    ],
    'editor' => env('DEBUGBAR_EDITOR', env('IGNITION_EDITOR', 'phpstorm')),
    'capture_ajax' => true,
    'add_ajax_timing' => true,
    'ajax_handler_auto_show' => true,
    'ajax_handler_enable_tab' => true,
    'defer_datasets' => false,
    'remote_sites_path' => env('DEBUGBAR_REMOTE_SITES_PATH'),
    'local_sites_path' => env('DEBUGBAR_LOCAL_SITES_PATH', env('IGNITION_LOCAL_SITES_PATH')),
    'storage' => [
        'enabled' => env('DEBUGBAR_STORAGE_ENABLED', true),
        'open' => env('DEBUGBAR_OPEN_STORAGE', false),
        'driver' => env('DEBUGBAR_STORAGE_DRIVER', 'file'),
        'path' => env('DEBUGBAR_STORAGE_PATH', storage_path('debugbar')),
        'connection' => env('DEBUGBAR_STORAGE_CONNECTION'),
        'provider' => env('DEBUGBAR_STORAGE_PROVIDER', ''),
    ],
    'use_dist_files' => true,
    'include_vendors' => true,
    'inject' => true,
    'route_prefix' => env('DEBUGBAR_ROUTE_PREFIX', '_debugbar'),
    'route_middleware' => [],
    'route_domain' => env('DEBUGBAR_ROUTE_DOMAIN'),
    'theme' => env('DEBUGBAR_THEME', 'auto'),
    'debug_backtrace_limit' => (int) env('DEBUGBAR_DEBUG_BACKTRACE_LIMIT', 25),
];
